name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: |
            ^README\.md$
            ^\.github/.*
            ^\.pre-commit-config\.yaml$
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JSON: true
